services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: alexito123
      POSTGRES_DB: vethope
    ports:
      - "5435:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
